# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snpSearchTool', '0002_messageclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoresrow',
            name='ref_strand',
        ),
        migrations.RemoveField(
            model_name='scoresrow',
            name='snp_strand',
        ),
    ]
