# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpSearchTool', '0003_auto_20160415_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoresrow',
            name='motif_len',
            field=models.IntegerField(default=-666),
        ),
    ]
