# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpSearchTool', '0004_scoresrow_motif_len'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoresrow',
            name='log_lik_ref',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='scoresrow',
            name='ref_strand',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='scoresrow',
            name='snp_strand',
            field=models.CharField(default='', max_length=1),
        ),
    ]
