# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpSearchTool', '0005_auto_20160415_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoresrow',
            name='log_enhance_odds',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='scoresrow',
            name='log_lik_ratio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='scoresrow',
            name='log_lik_snp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='scoresrow',
            name='log_reduce_odds',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='scoresrow',
            name='ref_end',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoresrow',
            name='ref_start',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoresrow',
            name='snp_end',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoresrow',
            name='snp_start',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scoresrow',
            name='motif_len',
            field=models.IntegerField(default=0),
        ),
    ]
