# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 21:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snpSearchTool', '0006_auto_20160415_2117'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='scoresrow',
            table='test_table',
        ),
    ]
