# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpSearchTool', '0007_auto_20160420_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoresrow',
            name='id',
        ),
        migrations.AlterField(
            model_name='scoresrow',
            name='snpid',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
