# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpSearchTool', '0008_auto_20160420_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoresrow',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scoresrow',
            name='snpid',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterModelTable(
            name='scoresrow',
            table='test_pipeline_tbl',
        ),
    ]
