# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snpSearchTool', '0010_auto_20160422_1943'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='scoresrow',
            table='snp_scores_1',
        ),
    ]
